/**
 * Capital Markets & Venture Capital vocabulary pack (TCO Capital Markets track).
 *
 * One record per term, organized into four sections. Each record carries the
 * five fields requested for the learning app, mapped onto the `Concept` model:
 *   whatItIs            -> Concept.whatItIs            (2-3 plain sentences)
 *   whyItMatters        -> Concept.whyItMatters        (student / operator / investor angle)
 *   flashcardShort      -> Concept.flashcardShort      (< 12-word gloss)
 *   flashcardDefinition -> Concept.flashcardDefinition (one tight sentence)
 *   source              -> a linked Resource (title + url citation)
 * Plus: `nuance` (the specific trip-up to surface) and `verified`.
 *
 * Provenance / `verified` flag:
 *   verified === true  -> the claim was adversarially fact-checked (3-vote, 2/3-to-kill)
 *                         in the deep-research run, sourced to a PRIMARY authority
 *                         (Y Combinator, a16z, NVCA) or a strongly-corroborated
 *                         secondary (Carta, govclab, iCapital).
 *   verified === false -> drafted from the SAME authoritative source families and a
 *                         cited reference, but not independently adjudicated in that
 *                         run. These are stable, textbook definitions; spot-check the
 *                         formula-bearing ones (anti-dilution, liquidation preference,
 *                         CAC/LTV, EV multiples) before shipping to recruits.
 *
 * Style constraints (match existing seed-data house style):
 *   - No em dashes (—) in flashcard fields; use commas, parentheses, or "like".
 *   - Flashcard shorts stay under 12 words. Definitions are one sentence.
 *
 * Sources skew to the families the brief requested: Y Combinator (SAFE primary
 * source), a16z ("16 Startup Metrics" / "16 More Startup Metrics"), NVCA model
 * legal documents (the canonical term-sheet / governance reference), and Carta /
 * govclab / iCapital for fund economics. Investopedia / CFI back the standard
 * valuation terms those families don't index cleanly.
 */

export type VocabSectionSlug =
  | "venture-financing"
  | "fund-mechanics"
  | "markets-metrics"
  | "diligence-terms";

export interface VocabSource {
  label: string;
  url: string;
}

export interface VocabTerm {
  section: VocabSectionSlug;
  name: string;
  slug: string;
  subtitle: string;
  difficulty: "FUNDAMENTALS" | "INTERMEDIATE" | "ADVANCED";
  sortOrder: number;
  whatItIs: string;
  whyItMatters: string;
  flashcardShort: string;
  flashcardDefinition: string;
  source: VocabSource;
  /** The specific nuance members trip on. Surface in the concept detail view. */
  nuance?: string;
  /** true = adversarially verified in the deep-research run; false = drafted from cited authority. */
  verified: boolean;
}

export const CAPITAL_MARKETS_TRACK = {
  slug: "capital-markets",
  name: "Capital Markets & Venture Capital",
  shortName: "Capital Markets",
  description:
    "The language of startup financing, fund economics, and market valuation, built for members from any background.",
  accentColor: "#4255FF",
  isPrimary: false,
  sortOrder: 2,
};

export const VOCAB_SECTIONS: { slug: VocabSectionSlug; name: string; description: string; sortOrder: number }[] = [
  {
    slug: "venture-financing",
    name: "Venture Financing",
    description: "How startups raise money and how ownership is divided across rounds.",
    sortOrder: 1,
  },
  {
    slug: "fund-mechanics",
    name: "Fund Mechanics",
    description: "How venture funds themselves work: who funds them, how managers get paid, and how returns are measured.",
    sortOrder: 2,
  },
  {
    slug: "markets-metrics",
    name: "Markets & Metrics",
    description: "Sizing markets and reading the numbers that drive startup and company valuation.",
    sortOrder: 3,
  },
  {
    slug: "diligence-terms",
    name: "Diligence & Terms",
    description: "The investigation and contractual terms that govern deals, control, and exits.",
    sortOrder: 4,
  },
];

export const CAPITAL_MARKETS_VOCAB: VocabTerm[] = [
  // ─── VENTURE FINANCING ──────────────────────────────────────────────────────
  {
    section: "venture-financing",
    name: "SAFE",
    slug: "safe",
    subtitle: "The standard 'invest now, get equity later' contract for early-stage rounds",
    difficulty: "FUNDAMENTALS",
    sortOrder: 1,
    whatItIs: `A SAFE (Simple Agreement for Future Equity) is a short investment contract a startup uses to raise early money fast. The investor pays cash now and, instead of receiving shares immediately, gets the right to shares later when the company does its next priced equity round. Y Combinator created it in 2013, and the 2018 "post-money" version is now the standard form.`,
    whyItMatters: `It is the dominant way pre-seed and seed startups raise (roughly 80-90% of recent pre-seed deals), so anyone touching early-stage startups meets it constantly. For founders the post-money SAFE makes dilution exactly calculable up front, which is both its main selling point and its main trap.`,
    flashcardShort: `Pay now, get equity later at the next priced round.`,
    flashcardDefinition: `A contract where an investor funds a startup today in exchange for shares issued at its next priced financing.`,
    source: { label: "Y Combinator, SAFE documents", url: "https://www.ycombinator.com/documents/" },
    nuance: `Post-money SAFE ownership is locked at signing as Purchase Amount / Post-Money Valuation Cap (e.g. $500k on a $5M cap = 10%). SAFEs do NOT dilute each other, so founders absorb all of it. Raising an amount equal to the cap leaves founders with 0%, and raising more would imply "negative" founder ownership. SAFE holders are still diluted by the new priced-round money and by the option-pool increase done at that round.`,
    verified: true,
  },
  {
    section: "venture-financing",
    name: "Priced Round",
    slug: "priced-round",
    subtitle: "A raise with an agreed per-share price and a fixed valuation",
    difficulty: "FUNDAMENTALS",
    sortOrder: 2,
    whatItIs: `A priced round is a fundraise where the company and investors agree on an actual per-share price, which means they first agree on a valuation. Investors buy newly issued preferred shares at that price, so everyone knows exactly what percentage of the company changed hands. Series A, B, and C are all priced rounds.`,
    whyItMatters: `Unlike a SAFE or convertible note, a priced round sets a hard valuation and issues real shares, triggering the full legal machinery (term sheet, board seats, liquidation preferences). It is the moment a startup's ownership and governance get formally locked in.`,
    flashcardShort: `Funding round with an agreed share price and valuation.`,
    flashcardDefinition: `A financing in which investors buy newly issued shares at a negotiated per-share price based on an agreed valuation.`,
    source: { label: "NVCA model legal documents", url: "https://nvca.org/model-legal-documents/" },
    verified: false,
  },
  {
    section: "venture-financing",
    name: "Series A / B / C",
    slug: "series-abc",
    subtitle: "The named, progressively larger priced rounds as a startup scales",
    difficulty: "FUNDAMENTALS",
    sortOrder: 3,
    whatItIs: `These are the named, sequential priced rounds a growing startup raises, each typically bigger and at a higher valuation than the last. Series A usually funds finding a repeatable business model, Series B funds scaling it, and Series C and beyond fund expansion, new markets, or pre-IPO growth. The letters are conventions, not legal categories.`,
    whyItMatters: `The stage tells you a lot at a glance: how proven the company is, how much money is involved, and what investors expect next. Operators and investors use the label to benchmark traction, risk, and valuation.`,
    flashcardShort: `Sequential, larger priced rounds as a startup scales.`,
    flashcardDefinition: `The named series of progressively larger equity rounds (A, then B, then C) that fund a startup from product-market fit through scale.`,
    source: { label: "Y Combinator library", url: "https://www.ycombinator.com/library" },
    verified: false,
  },
  {
    section: "venture-financing",
    name: "Term Sheet",
    slug: "term-sheet",
    subtitle: "The mostly non-binding blueprint of a deal's key terms",
    difficulty: "FUNDAMENTALS",
    sortOrder: 4,
    whatItIs: `A term sheet is a short, mostly non-binding document that lays out the key economic and control terms of an investment before the long legal contracts are drafted. It covers things like valuation, amount invested, liquidation preference, board seats, and investor protections. Once both sides sign it, lawyers turn it into the binding financing documents.`,
    whyItMatters: `It is where the real negotiation happens; the final legal docs mostly just formalize it. Knowing how to read one tells you who controls the company and who gets paid first in an exit.`,
    flashcardShort: `Non-binding summary of a deal's key economic and control terms.`,
    flashcardDefinition: `A preliminary document outlining the main valuation, economic, and governance terms of a financing before binding contracts are written.`,
    source: { label: "NVCA model term sheet", url: "https://nvca.org/model-legal-documents/" },
    verified: false,
  },
  {
    section: "venture-financing",
    name: "Cap Table",
    slug: "cap-table",
    subtitle: "The master ledger of who owns what in a company",
    difficulty: "FUNDAMENTALS",
    sortOrder: 5,
    whatItIs: `A capitalization table (cap table) is the master list of who owns what in a company: founders, employees, and investors, plus options, SAFEs, and convertible notes. It tracks how many shares each party holds and what percentage of the company that represents. Every financing updates it.`,
    whyItMatters: `It is the single source of truth for ownership and dilution. Founders use it to model how a raise affects their stake; investors use it to confirm what they are actually buying.`,
    flashcardShort: `The ledger of who owns what in a company.`,
    flashcardDefinition: `A spreadsheet or ledger listing every shareholder, their share count, and their ownership percentage, including options and convertibles.`,
    source: { label: "Carta, equity learning hub", url: "https://carta.com/learn/" },
    nuance: `Cap-table math trips people up on fully-diluted vs issued shares and the "option-pool shuffle": a new investor often requires the option pool to be expanded BEFORE their money goes in, so the expansion dilutes existing holders (founders), not the new investor.`,
    verified: false,
  },
  {
    section: "venture-financing",
    name: "Dilution",
    slug: "dilution",
    subtitle: "Your ownership percentage shrinking as new shares are issued",
    difficulty: "FUNDAMENTALS",
    sortOrder: 6,
    whatItIs: `Dilution is the drop in your ownership percentage when a company issues new shares. If you own 10% and the company creates a big batch of new shares for investors or employees, your slice of the now-larger pie shrinks even though your share count is unchanged. It is a normal cost of raising money.`,
    whyItMatters: `Every founder and early employee gets diluted across rounds; understanding it is the difference between owning 5% or 0.5% at exit. Investors care because pro-rata rights and anti-dilution clauses exist specifically to manage it.`,
    flashcardShort: `Your ownership percentage shrinking as new shares are issued.`,
    flashcardDefinition: `The reduction in existing holders' ownership percentage that occurs when a company issues additional shares.`,
    source: { label: "Y Combinator library", url: "https://www.ycombinator.com/library" },
    verified: false,
  },
  {
    section: "venture-financing",
    name: "Pre / Post-Money Valuation",
    slug: "pre-post-money-valuation",
    subtitle: "What a company is worth before vs after new investment goes in",
    difficulty: "FUNDAMENTALS",
    sortOrder: 7,
    whatItIs: `Pre-money valuation is what a company is judged to be worth right before it takes in new investment; post-money is that value plus the new cash (post-money = pre-money + amount raised). The investor's ownership equals their investment divided by the post-money valuation. So a $2M investment at an $8M pre-money ($10M post) buys 20%.`,
    whyItMatters: `The pre/post distinction decides exactly how much of the company investors get. Founders who quote "valuation" without specifying which one can accidentally give away far more than they intended.`,
    flashcardShort: `Company value before (pre) vs after (post) new investment.`,
    flashcardDefinition: `Pre-money is a company's value before new funding; post-money adds the new investment, and ownership equals investment divided by post-money.`,
    source: { label: "Investopedia, Post-Money Valuation", url: "https://www.investopedia.com/terms/p/postmoneyvaluation.asp" },
    nuance: `Investor ownership = investment / post-money. Confusing pre- and post-money is a classic founder error; on an $8M pre / $10M post deal the investor owns 20%, not 25%.`,
    verified: false,
  },
  {
    section: "venture-financing",
    name: "Option Pool",
    slug: "option-pool",
    subtitle: "Shares reserved to grant future employees as stock options",
    difficulty: "INTERMEDIATE",
    sortOrder: 8,
    whatItIs: `An option pool is a block of shares set aside to grant to future employees as stock options. It is carved out of the cap table, usually at an investor's request, as part of a financing. A typical pool is around 10-20% of the company.`,
    whyItMatters: `Pools are how startups pay talent they can't afford in cash. The catch: investors usually insist the pool be created or topped up from the PRE-money valuation, so the dilution falls on founders, not the new investor.`,
    flashcardShort: `Shares reserved to grant employees as stock options.`,
    flashcardDefinition: `A reserved block of equity set aside for future employee stock-option grants, typically 10-20% of the company.`,
    source: { label: "NVCA model legal documents", url: "https://nvca.org/model-legal-documents/" },
    nuance: `The "option pool shuffle": because the pool is usually added pre-money, expanding it lowers the effective price founders receive and dilutes them, while the incoming investor's percentage is protected.`,
    verified: false,
  },
  {
    section: "venture-financing",
    name: "Liquidation Preference",
    slug: "liquidation-preference",
    subtitle: "Who gets paid first, and how much, when a company sells",
    difficulty: "INTERMEDIATE",
    sortOrder: 9,
    whatItIs: `A liquidation preference decides who gets paid first, and how much, when a company is sold or wound down. Preferred investors with a "1x" preference get their money back before common shareholders (founders, employees) see anything. It protects investors when an exit is smaller than hoped.`,
    whyItMatters: `In a modest exit, a stack of preferences can mean founders and employees get little or nothing while investors are made whole. It is one of the most important and most overlooked terms in a deal.`,
    flashcardShort: `Who gets paid first, and how much, in an exit.`,
    flashcardDefinition: `A term giving preferred investors the right to recover a set multiple of their investment before common holders are paid in a sale or liquidation.`,
    source: { label: "NVCA model legal documents", url: "https://nvca.org/model-legal-documents/" },
    nuance: `Watch "1x non-participating" (investor takes the greater of their money back OR converting to common) vs "participating" (investor takes their money back AND shares the rest, i.e. "double-dips"). Non-participating 1x is the founder-friendly market standard.`,
    verified: false,
  },
  {
    section: "venture-financing",
    name: "Pro Rata",
    slug: "pro-rata",
    subtitle: "An investor's right to invest more to hold their percentage",
    difficulty: "INTERMEDIATE",
    sortOrder: 10,
    whatItIs: `A pro-rata right lets an existing investor put more money into future rounds to keep their ownership percentage from shrinking. If they own 10% and the company raises again, the right lets them buy enough of the new round to stay at 10%. It is a way to defend against dilution.`,
    whyItMatters: `For investors, pro-rata rights are how they keep backing winners and protect their stake in breakout companies. For founders, granting them affects how much room is left for new investors in later rounds.`,
    flashcardShort: `Right to invest more to keep your ownership percentage.`,
    flashcardDefinition: `An investor's contractual right to participate in future rounds enough to maintain their existing ownership percentage.`,
    source: { label: "NVCA Investors' Rights Agreement", url: "https://nvca.org/model-legal-documents/" },
    verified: false,
  },
  {
    section: "venture-financing",
    name: "Convertible Note",
    slug: "convertible-note",
    subtitle: "An early-stage loan designed to convert into equity",
    difficulty: "INTERMEDIATE",
    sortOrder: 11,
    whatItIs: `A convertible note is an early-stage loan that is designed to convert into equity instead of being repaid in cash. The investor lends money that later turns into shares at the next priced round, usually with a discount and/or a valuation cap as a reward for investing early. Unlike a SAFE, it is actual debt, so it carries interest and a maturity date.`,
    whyItMatters: `It was the original "invest now, price later" instrument before SAFEs and is still common. The debt features (interest, maturity) create real obligations and edge cases a SAFE avoids, which is why founders should know the difference.`,
    flashcardShort: `Early-stage loan that converts into equity later.`,
    flashcardDefinition: `A short-term debt instrument that converts into equity at a future priced round, typically with a discount or valuation cap, plus interest and a maturity date.`,
    source: { label: "Y Combinator library", url: "https://www.ycombinator.com/library" },
    nuance: `Key contrast vs SAFE: a convertible note is debt (it accrues interest and has a maturity date at which it could be called or must convert); a SAFE is not debt and has neither.`,
    verified: false,
  },
  {
    section: "venture-financing",
    name: "Vesting / Cliff",
    slug: "vesting-cliff",
    subtitle: "Earning your equity over time, with a one-year cliff",
    difficulty: "FUNDAMENTALS",
    sortOrder: 12,
    whatItIs: `Vesting is the schedule by which founders or employees earn their shares or options over time, rather than owning them all on day one. A standard schedule is four years with a one-year "cliff," meaning you earn nothing until you have stayed a full year, then 25% vests at once and the rest accrues monthly. Leave early and you forfeit the unvested portion.`,
    whyItMatters: `Vesting keeps teams committed and protects the cap table if a co-founder quits in month three. Anyone joining a startup needs to understand their schedule because it determines what they actually keep.`,
    flashcardShort: `Earning your equity over time, with a one-year cliff.`,
    flashcardDefinition: `A schedule under which equity is earned gradually over time (commonly four years), with a cliff period before any of it vests.`,
    source: { label: "Investopedia, Vesting", url: "https://www.investopedia.com/terms/v/vesting.asp" },
    nuance: `The "cliff" is the gotcha: in standard 4-year / 1-year-cliff vesting you earn zero equity if you leave before the 12-month mark, then 25% vests all at once on the cliff date.`,
    verified: false,
  },

  // ─── FUND MECHANICS ─────────────────────────────────────────────────────────
  {
    section: "fund-mechanics",
    name: "LP (Limited Partner)",
    slug: "lp",
    subtitle: "The investors who put money into a fund but don't run it",
    difficulty: "FUNDAMENTALS",
    sortOrder: 1,
    whatItIs: `Limited Partners are the investors who put money INTO a venture or private-equity fund but don't run it. They are typically pension funds, university endowments, family offices, and wealthy individuals. They commit capital and share in the returns, but their liability and day-to-day involvement are "limited."`,
    whyItMatters: `LPs are the ultimate source of VC money; understanding their incentives (they want strong, timely returns to justify the risk and illiquidity) explains why funds behave the way they do. Anyone raising a fund is really selling to LPs.`,
    flashcardShort: `Investors who fund a VC fund but don't run it.`,
    flashcardDefinition: `The outside investors (endowments, pensions, family offices) who commit capital to a fund but leave management to the GP.`,
    source: { label: "Carta, private funds learning hub", url: "https://carta.com/learn/private-funds/" },
    verified: false,
  },
  {
    section: "fund-mechanics",
    name: "GP (General Partner)",
    slug: "gp",
    subtitle: "The firm that runs the fund and makes the investments",
    difficulty: "FUNDAMENTALS",
    sortOrder: 2,
    whatItIs: `The General Partner is the firm (and the people) that actually runs a venture or PE fund: raising it, picking investments, and managing the portfolio. GPs invest the LPs' money alongside a small slice of their own. They earn a management fee plus a share of the profits called carry.`,
    whyItMatters: `GPs are the "VCs" founders pitch and the managers LPs entrust with their capital. Their compensation structure (fees plus carry) shapes nearly every incentive in the venture ecosystem.`,
    flashcardShort: `The firm that runs the fund and picks investments.`,
    flashcardDefinition: `The manager of a fund who raises capital, makes investment decisions, and earns a management fee plus carried interest.`,
    source: { label: "Carta, private funds learning hub", url: "https://carta.com/learn/private-funds/" },
    verified: false,
  },
  {
    section: "fund-mechanics",
    name: "Carry (Carried Interest)",
    slug: "carried-interest",
    subtitle: "The GP's share of fund profits, standardly 20%",
    difficulty: "INTERMEDIATE",
    sortOrder: 3,
    whatItIs: `Carried interest, or "carry," is the share of a fund's profits that the GP keeps as their performance reward, standardly 20%. So if a fund turns $100M into $300M, the $200M profit yields the GP $40M in carry. It is paid only after LPs get their capital back (and, where one exists, a preferred return).`,
    whyItMatters: `Carry is how VCs get rich, and it aligns them with LPs: they only win big if the fund wins big. The mechanics of WHEN carry gets paid (the "waterfall") are heavily negotiated.`,
    flashcardShort: `The GP's roughly 20% cut of fund profits.`,
    flashcardDefinition: `The share of fund profits (typically 20%) paid to the GP as performance compensation after LPs are repaid.`,
    source: { label: "Carta, carried interest", url: "https://carta.com/learn/private-funds/management/carried-interest/" },
    nuance: `Carry sits at the end of a distribution "waterfall." Where a hurdle / preferred return exists, the GP earns nothing until LPs clear it; a "GP catch-up" tier then lets the GP collect carry computed from the first dollar of profit.`,
    verified: true,
  },
  {
    section: "fund-mechanics",
    name: "Management Fee",
    slug: "management-fee",
    subtitle: "The annual fee LPs pay the GP to operate the fund",
    difficulty: "INTERMEDIATE",
    sortOrder: 4,
    whatItIs: `The management fee is the annual fee LPs pay the GP to operate the fund, classically 2% of the money committed. On a $50M fund, that is $1M a year, used to pay salaries, rent, and diligence costs. It is charged whether or not the fund is performing well.`,
    whyItMatters: `It keeps the lights on at the fund, but it also eats into LP returns, which is why fee structures are scrutinized. After the investment period, the fee basis usually "steps down."`,
    flashcardShort: `Roughly 2% annual fee LPs pay to run the fund.`,
    flashcardDefinition: `An annual fee (classically 2% of committed capital) paid by LPs to cover the fund's operating costs.`,
    source: { label: "GovCLab, venture fund economics", url: "https://govclab.com/2023/08/09/venture-fund-economics/" },
    nuance: `The 2% is usually charged on COMMITTED capital during the roughly 5-year investment period, then "steps down" to invested capital (or a lower rate) afterward. Larger funds sometimes charge 2.5%.`,
    verified: true,
  },
  {
    section: "fund-mechanics",
    name: "2-and-20",
    slug: "two-and-twenty",
    subtitle: "The standard fund pay structure: 2% fee plus 20% of profits",
    difficulty: "INTERMEDIATE",
    sortOrder: 5,
    whatItIs: `"2-and-20" is shorthand for the standard fund fee structure: a 2% annual management fee plus 20% carried interest on profits. The 2% funds operations; the 20% rewards performance. It is the default compensation model across venture and private equity.`,
    whyItMatters: `It is the single most important pairing for understanding fund economics and why GPs behave as they do. LPs effectively pay 2% a year to access deals and surrender 20% of the upside in exchange for management's skill.`,
    flashcardShort: `2% annual fee plus 20% of profits.`,
    flashcardDefinition: `The standard fund compensation model: a 2% annual management fee plus 20% carried interest on profits.`,
    source: { label: "GovCLab, venture fund economics", url: "https://govclab.com/2023/08/09/venture-fund-economics/" },
    nuance: `Carry is paid through a "waterfall": (1) return LP capital, (2) pay any preferred return / hurdle (around 8% in PE, usually NONE in VC), (3) GP catch-up, (4) split the rest roughly 80/20. "American" waterfalls pay carry deal-by-deal; "European" ones pay only after the whole fund is repaid.`,
    verified: true,
  },
  {
    section: "fund-mechanics",
    name: "Capital Call",
    slug: "capital-call",
    subtitle: "When the GP draws down committed capital from LPs",
    difficulty: "INTERMEDIATE",
    sortOrder: 6,
    whatItIs: `A capital call (or "drawdown") is when the GP asks LPs to actually send in a portion of the money they committed. LPs don't hand over the full amount up front; they pledge it, and the GP calls it in tranches as deals come up. LPs are contractually obligated to deliver when called.`,
    whyItMatters: `It explains why "committed" capital and "deployed" capital differ, and why LPs must keep cash ready. Missing a capital call carries steep penalties.`,
    flashcardShort: `GP drawing down committed capital from LPs as needed.`,
    flashcardDefinition: `A GP's request for LPs to transfer a portion of their previously committed capital, drawn down as investments are made.`,
    source: { label: "Investopedia, Capital Call", url: "https://www.investopedia.com/terms/c/capitalcall.asp" },
    verified: false,
  },
  {
    section: "fund-mechanics",
    name: "Vintage Year",
    slug: "vintage-year",
    subtitle: "The year a fund starts investing, used for benchmarking",
    difficulty: "INTERMEDIATE",
    sortOrder: 7,
    whatItIs: `A fund's vintage year is the year it first starts investing capital (or its first close). It is used like a wine vintage: funds are benchmarked against other funds of the same vintage because they faced the same market conditions. A 2021 fund and a 2009 fund lived through very different environments.`,
    whyItMatters: `Comparing a fund's returns to peers requires matching vintages; a great 2009 fund and a mediocre 2021 fund can't be judged on raw numbers alone. LPs use vintage to diversify across market cycles.`,
    flashcardShort: `The year a fund starts investing, used for benchmarking.`,
    flashcardDefinition: `The year a fund begins deploying capital, used to compare its performance against peers from the same period.`,
    source: { label: "Investopedia, Vintage Year", url: "https://www.investopedia.com/terms/v/vintage-year.asp" },
    verified: false,
  },
  {
    section: "fund-mechanics",
    name: "DPI",
    slug: "dpi",
    subtitle: "Cash actually returned to LPs per dollar invested",
    difficulty: "ADVANCED",
    sortOrder: 8,
    whatItIs: `DPI (Distributions to Paid-In) measures how much actual cash a fund has returned to its LPs relative to what they put in. A DPI of 1.0x means LPs have gotten all their money back; 0.5x means half. It counts only realized, in-hand distributions, not paper gains.`,
    whyItMatters: `DPI is the "show me the money" metric; it can't be inflated by optimistic markups. LPs ultimately care about cash returned, so a high DPI is the truest sign a fund delivered.`,
    flashcardShort: `Cash actually returned to LPs per dollar invested.`,
    flashcardDefinition: `A multiple measuring realized cash distributions returned to LPs divided by the capital they paid in.`,
    source: { label: "Carta, fund performance metrics", url: "https://carta.com/learn/private-funds/management/fund-performance/" },
    nuance: `DPI counts ONLY realized cash and ignores both unrealized holdings and timing (no time-value adjustment). It is the realized / liquidity multiple, the opposite end from RVPI (the unrealized part).`,
    verified: true,
  },
  {
    section: "fund-mechanics",
    name: "TVPI",
    slug: "tvpi",
    subtitle: "Total value (cash plus holdings) per dollar invested",
    difficulty: "ADVANCED",
    sortOrder: 9,
    whatItIs: `TVPI (Total Value to Paid-In) measures a fund's total value, both cash already distributed AND the current value of investments it still holds, relative to the money LPs paid in. It equals DPI (realized) plus RVPI (unrealized). A TVPI of 2.4x means the fund has generated 2.4x the invested capital on paper and in cash combined.`,
    whyItMatters: `It is the headline "how is this fund doing overall" multiple, capturing both money returned and money still at work. Because part of it is unrealized, it can move as markups change.`,
    flashcardShort: `Total value (cash plus holdings) per dollar invested.`,
    flashcardDefinition: `A multiple of a fund's total value (distributions plus remaining holdings) over the capital LPs paid in, where TVPI equals DPI plus RVPI.`,
    source: { label: "Carta, fund performance metrics", url: "https://carta.com/learn/private-funds/management/fund-performance/" },
    nuance: `TVPI = DPI + RVPI. Because RVPI (the unrealized part) rests on the GP's current marks, TVPI can be optimistic until those holdings actually exit. The identity only holds when all three are measured on the same basis (all gross or all net).`,
    verified: true,
  },
  {
    section: "fund-mechanics",
    name: "MOIC",
    slug: "moic",
    subtitle: "How many times the invested capital multiplied",
    difficulty: "ADVANCED",
    sortOrder: 10,
    whatItIs: `MOIC (Multiple on Invested Capital) is the simplest return multiple: total value created (realized plus unrealized) divided by the capital invested. A 3x MOIC means the investment is worth three times what was put in. It deliberately ignores how long that took.`,
    whyItMatters: `MOIC answers "how many times did we multiply the money?" in one clean number. But because it ignores time, a 2x in 2 years and a 2x in 12 years look identical, which is why it must be paired with IRR.`,
    flashcardShort: `How many times the invested capital multiplied.`,
    flashcardDefinition: `The ratio of total value (realized plus unrealized) to invested capital, ignoring the timing of cash flows.`,
    source: { label: "Carta, fund performance metrics", url: "https://carta.com/learn/private-funds/management/fund-performance/" },
    nuance: `MOIC ignores TIME, so it can't distinguish a fast double from a slow one. It is often quoted gross (before fees and carry); a "net MOIC" includes them. Closely related to TVPI but usually measured at the deal level.`,
    verified: true,
  },
  {
    section: "fund-mechanics",
    name: "IRR",
    slug: "irr",
    subtitle: "Annualized return that accounts for cash-flow timing",
    difficulty: "ADVANCED",
    sortOrder: 11,
    whatItIs: `IRR (Internal Rate of Return) is the annualized percentage return of a fund, the single rate that makes the value of all the money in and out net to zero. Unlike a simple multiple, it accounts for WHEN cash moved, so getting money back sooner produces a higher IRR. VC LPs often target a net IRR around 20%.`,
    whyItMatters: `IRR is how time-sensitive returns get compared across funds and against public markets. Because timing matters, early distributions and capital-call timing can swing it dramatically.`,
    flashcardShort: `Annualized return that accounts for cash-flow timing.`,
    flashcardDefinition: `The annualized discount rate that sets the net present value of all a fund's cash flows to zero, capturing the timing of returns.`,
    source: { label: "Carta, fund performance metrics", url: "https://carta.com/learn/private-funds/management/fund-performance/" },
    nuance: `IRR is the only one of these metrics that incorporates TIMING (MOIC / TVPI / DPI don't). The roughly 20% VC target is aspirational / top-quartile; typical realized VC net IRR is closer to 10-15%. It can also be flattered by early distributions and subscription-line financing.`,
    verified: true,
  },
  {
    section: "fund-mechanics",
    name: "J-Curve",
    slug: "j-curve",
    subtitle: "Funds dip negative early, then curve up to gains",
    difficulty: "ADVANCED",
    sortOrder: 12,
    whatItIs: `The J-curve describes the typical shape of a fund's returns over its life: it dips into negative territory early, then curves up as investments mature and exits happen. Early on, management fees and startup costs are spent while investments haven't paid off yet, so returns look bad. The trough usually lasts about three to five years.`,
    whyItMatters: `It tells LPs not to panic at early losses; weak first-year numbers are normal and expected. Understanding the J-curve is key to judging a fund at the right point in its life.`,
    flashcardShort: `Funds dip negative early, then curve up to gains.`,
    flashcardDefinition: `The trajectory of fund returns that starts negative (fees, immature investments) before rising as exits occur, tracing a J shape.`,
    source: { label: "Carta, fund performance metrics", url: "https://carta.com/learn/private-funds/management/fund-performance/" },
    nuance: `The early dip is driven by upfront fees and back-loaded distributions, not bad investing. It is why DPI stays near zero for years and why judging a young fund on DPI alone is misleading.`,
    verified: true,
  },

  // ─── MARKETS & METRICS ──────────────────────────────────────────────────────
  {
    section: "markets-metrics",
    name: "TAM / SAM / SOM",
    slug: "tam-sam-som",
    subtitle: "Nested market sizes: total, serviceable, obtainable",
    difficulty: "FUNDAMENTALS",
    sortOrder: 1,
    whatItIs: `These three nested numbers size a market. TAM (Total Addressable Market) is the total demand if you captured 100% of everyone who could ever use the product. SAM (Serviceable Addressable Market) is the slice you can actually serve given your model and geography. SOM (Serviceable Obtainable Market) is the realistic chunk you can win in the near term.`,
    whyItMatters: `Investors use market sizing to judge whether a startup can get big enough to matter. Founders who quote a giant TAM without a credible SAM and SOM signal they haven't thought hard about who actually buys.`,
    flashcardShort: `Nested market sizes: total, serviceable, obtainable.`,
    flashcardDefinition: `A framework sizing a market in three tiers, total demand (TAM), the serviceable portion (SAM), and the realistically winnable share (SOM).`,
    source: { label: "a16z, 16 Startup Metrics", url: "https://a16z.com/16-startup-metrics/" },
    verified: false,
  },
  {
    section: "markets-metrics",
    name: "ARR / MRR",
    slug: "arr-mrr",
    subtitle: "Predictable yearly (ARR) or monthly (MRR) subscription revenue",
    difficulty: "FUNDAMENTALS",
    sortOrder: 2,
    whatItIs: `ARR (Annual Recurring Revenue) and MRR (Monthly Recurring Revenue) measure the predictable, subscription-based revenue a company earns each year or month. They count only recurring contract revenue and deliberately EXCLUDE one-time fees, setup charges, and variable usage. ARR is roughly MRR times twelve.`,
    whyItMatters: `Recurring revenue is the lifeblood of SaaS valuation; investors pay far more for predictable ARR than for one-off sales. Mislabeling one-time revenue as ARR overstates the health of the business.`,
    flashcardShort: `Predictable yearly (ARR) or monthly (MRR) subscription revenue.`,
    flashcardDefinition: `The recurring subscription revenue a company earns annually (ARR) or monthly (MRR), excluding one-time and usage-based fees.`,
    source: { label: "a16z, 16 More Startup Metrics", url: "https://a16z.com/16-more-startup-metrics/" },
    nuance: `Per a16z, ARR is NOT "annual run rate." Taking one good month's total bookings and multiplying by 12 overstates ARR, because it sweeps in one-time and variable fees that aren't actually recurring.`,
    verified: true,
  },
  {
    section: "markets-metrics",
    name: "Net Revenue Retention",
    slug: "net-revenue-retention",
    subtitle: "Revenue kept and grown from existing customers, yearly",
    difficulty: "INTERMEDIATE",
    sortOrder: 3,
    whatItIs: `Net Revenue Retention (NRR) measures how much recurring revenue you keep, and grow, from your EXISTING customers over a year, after accounting for upgrades, downgrades, and churn, but ignoring brand-new customers. An NRR of 120% means last year's customers are now paying 20% more in total, even before adding anyone new. Below 100% means the existing base is shrinking.`,
    whyItMatters: `NRR above 100% means a company grows even if it stops acquiring customers, the holy grail for SaaS investors. It is one of the strongest predictors of durable, efficient growth.`,
    flashcardShort: `Revenue kept and grown from existing customers, yearly.`,
    flashcardDefinition: `The percentage of recurring revenue retained from existing customers over a period, including expansion and net of churn and downgrades.`,
    source: { label: "a16z, 16 More Startup Metrics", url: "https://a16z.com/16-more-startup-metrics/" },
    nuance: `NRR excludes new-customer revenue, so above 100% signals the existing base expands on its own. Don't confuse it with gross retention, which caps at 100% because it ignores upsell.`,
    verified: false,
  },
  {
    section: "markets-metrics",
    name: "Burn Rate",
    slug: "burn-rate",
    subtitle: "How fast a company spends cash each month",
    difficulty: "FUNDAMENTALS",
    sortOrder: 4,
    whatItIs: `Burn rate is how fast a company spends cash that it isn't yet earning back, usually quoted per month. "Gross burn" is total monthly cash out; "net burn" is cash out minus cash in. A startup burning $200k a month net is depleting its bank account by that much every month.`,
    whyItMatters: `Burn rate plus cash in the bank determines how long a company survives before it must raise again or become profitable. It is the number that keeps founders up at night.`,
    flashcardShort: `How fast a company spends cash each month.`,
    flashcardDefinition: `The rate at which a company depletes its cash reserves, typically measured per month (gross out, or net of revenue).`,
    source: { label: "a16z, 16 Startup Metrics", url: "https://a16z.com/16-startup-metrics/" },
    verified: false,
  },
  {
    section: "markets-metrics",
    name: "Runway",
    slug: "runway",
    subtitle: "Months of cash left at the current burn rate",
    difficulty: "FUNDAMENTALS",
    sortOrder: 5,
    whatItIs: `Runway is how many months a company can keep operating before it runs out of cash, calculated as cash in the bank divided by net monthly burn. With $2.4M in the bank and $200k net burn, runway is 12 months. It is the countdown clock of a startup.`,
    whyItMatters: `Runway dictates urgency: it tells founders when they must raise, cut costs, or hit profitability. Investors check it to gauge how much pressure a company is under.`,
    flashcardShort: `Months of cash left at the current burn rate.`,
    flashcardDefinition: `The length of time a company can operate before exhausting its cash, equal to cash on hand divided by net monthly burn.`,
    source: { label: "a16z, 16 Startup Metrics", url: "https://a16z.com/16-startup-metrics/" },
    nuance: `Runway = cash / net burn. Founders typically want to raise with 6+ months of runway left, since fundraising itself takes months.`,
    verified: false,
  },
  {
    section: "markets-metrics",
    name: "CAC / LTV",
    slug: "cac-ltv",
    subtitle: "Cost to win a customer vs their lifetime value",
    difficulty: "INTERMEDIATE",
    sortOrder: 6,
    whatItIs: `CAC (Customer Acquisition Cost) is what you spend on sales and marketing to win one new customer. LTV (Lifetime Value) is the total profit you expect from that customer over the whole relationship. Comparing them (the LTV/CAC ratio) shows whether acquiring customers actually pays off.`,
    whyItMatters: `If it costs more to acquire a customer than they are ever worth, growth destroys value. Investors look for an LTV/CAC ratio of roughly 3x or higher and a CAC payback period typically within 12-18 months.`,
    flashcardShort: `Cost to win a customer vs their lifetime value.`,
    flashcardDefinition: `CAC is the cost to acquire a customer; LTV is the lifetime profit they generate, and their ratio measures acquisition efficiency.`,
    source: { label: "a16z, 16 Startup Metrics", url: "https://a16z.com/16-startup-metrics/" },
    nuance: `Healthy benchmark is LTV/CAC of about 3x or more. a16z warns LTV must be computed on NET PROFIT / contribution margin, not on revenue or even gross margin, and must account for churn, or it flatters the business.`,
    verified: false,
  },
  {
    section: "markets-metrics",
    name: "EV/Revenue & EV/EBITDA Multiples",
    slug: "ev-multiples",
    subtitle: "Company value as a multiple of revenue or earnings",
    difficulty: "ADVANCED",
    sortOrder: 7,
    whatItIs: `These are valuation shortcuts that express a company's Enterprise Value (its total value to all investors, debt plus equity minus cash) as a multiple of a financial metric. EV/Revenue compares value to sales and is used for fast-growing or not-yet-profitable companies; EV/EBITDA compares value to operating cash earnings and is used for profitable ones. A company trading at "10x revenue" has an EV ten times its annual sales.`,
    whyItMatters: `Multiples are how investors quickly compare what companies are worth relative to peers. Which multiple you use signals the company's stage: revenue multiples for growth, EBITDA multiples for maturity.`,
    flashcardShort: `Company value as a multiple of revenue or earnings.`,
    flashcardDefinition: `Valuation ratios expressing enterprise value as a multiple of revenue (for growth firms) or EBITDA (for profitable firms).`,
    source: { label: "Investopedia, EV/EBITDA", url: "https://www.investopedia.com/terms/e/ev-ebitda.asp" },
    nuance: `Enterprise Value, not market cap, sits on top because it includes debt and nets out cash, making companies with different capital structures comparable. EV/Revenue suits pre-profit growth firms; EV/EBITDA suits profitable ones.`,
    verified: false,
  },
  {
    section: "markets-metrics",
    name: "DCF",
    slug: "dcf",
    subtitle: "Valuing a company by its discounted future cash flows",
    difficulty: "ADVANCED",
    sortOrder: 8,
    whatItIs: `A Discounted Cash Flow (DCF) values a company by projecting the cash it will generate in the future and "discounting" those amounts back to today's dollars, since money later is worth less than money now. Add up all those present values and you get an estimated intrinsic value. It is the most fundamentals-driven valuation method.`,
    whyItMatters: `DCF forces you to state explicit assumptions about growth, margins, and risk rather than just copying market multiples. It is the analytical backbone of valuation, though it is very sensitive to its inputs.`,
    flashcardShort: `Valuing a company by its discounted future cash flows.`,
    flashcardDefinition: `A valuation method that estimates intrinsic value by projecting future cash flows and discounting them to present value.`,
    source: { label: "Investopedia, Discounted Cash Flow", url: "https://www.investopedia.com/terms/d/dcf.asp" },
    nuance: `DCF is hugely sensitive to two assumptions, the discount rate and the terminal growth rate, so small changes swing the output wildly. It is rarely used for early-stage startups whose cash flows are too uncertain.`,
    verified: false,
  },
  {
    section: "markets-metrics",
    name: "Public Comps",
    slug: "public-comps",
    subtitle: "Valuing a company against similar public companies' multiples",
    difficulty: "ADVANCED",
    sortOrder: 9,
    whatItIs: `Public comparables ("comps") value a company by looking at how similar publicly traded companies are priced. You take peers in the same industry, calculate their valuation multiples (like EV/Revenue or EV/EBITDA), and apply those to the company you are valuing. It answers "what is the market paying for businesses like this?"`,
    whyItMatters: `Comps ground a valuation in real, current market prices rather than theoretical models. Investors and bankers use them constantly to sanity-check what a company should be worth.`,
    flashcardShort: `Valuing a company against similar public companies' multiples.`,
    flashcardDefinition: `A relative-valuation method that prices a company using the trading multiples of comparable publicly listed peers.`,
    source: { label: "Corporate Finance Institute, Comparable Company Analysis", url: "https://corporatefinanceinstitute.com/resources/valuation/comparable-company-analysis/" },
    verified: false,
  },

  // ─── DILIGENCE & TERMS ──────────────────────────────────────────────────────
  {
    section: "diligence-terms",
    name: "Due Diligence",
    slug: "due-diligence",
    subtitle: "Investigating a company before closing a deal",
    difficulty: "FUNDAMENTALS",
    sortOrder: 1,
    whatItIs: `Due diligence is the investigation an investor or acquirer runs before closing a deal, verifying that a company is what it claims to be. It covers financials, legal structure, technology, customers, and the team. The goal is to surface risks and confirm the story before money changes hands.`,
    whyItMatters: `It is where deals get validated or fall apart; surprises found in diligence can kill a term sheet or cut the price. Founders who keep clean records sail through it; messy ones lose time and leverage.`,
    flashcardShort: `Investigating a company before closing a deal.`,
    flashcardDefinition: `The investigative process by which an investor or acquirer verifies a company's financial, legal, and operational claims before closing.`,
    source: { label: "Investopedia, Due Diligence", url: "https://www.investopedia.com/terms/d/duediligence.asp" },
    verified: false,
  },
  {
    section: "diligence-terms",
    name: "Data Room",
    slug: "data-room",
    subtitle: "Secure online folder of documents for diligence",
    difficulty: "FUNDAMENTALS",
    sortOrder: 2,
    whatItIs: `A data room is the secure, online folder where a company shares its confidential documents with investors or acquirers during diligence. It holds the cap table, financials, contracts, IP, and legal records, all organized for review. Access is controlled and tracked.`,
    whyItMatters: `A well-organized data room speeds up a raise or sale and signals competence; a chaotic one slows everything and spooks investors. It is the practical workspace where diligence actually happens.`,
    flashcardShort: `Secure online folder of documents for diligence.`,
    flashcardDefinition: `A controlled-access digital repository where a company shares confidential documents with investors or buyers during due diligence.`,
    source: { label: "Investopedia, Data Room", url: "https://www.investopedia.com/terms/d/data-room.asp" },
    verified: false,
  },
  {
    section: "diligence-terms",
    name: "Board Seat",
    slug: "board-seat",
    subtitle: "A position on the board that governs the company",
    difficulty: "INTERMEDIATE",
    sortOrder: 3,
    whatItIs: `A board seat is a position on a company's board of directors, the small group that oversees the company and makes its biggest decisions (hiring or firing the CEO, approving budgets, green-lighting a sale). Lead investors usually negotiate a board seat as part of a priced round. Board composition determines who ultimately controls the company.`,
    whyItMatters: `Whoever controls the board controls the company's fate at key moments. Founders watch board composition closely because losing board control can mean losing the company even while still owning a big chunk of it.`,
    flashcardShort: `A seat on the board that governs the company.`,
    flashcardDefinition: `A position on a company's board of directors, often granted to lead investors, carrying control over major corporate decisions.`,
    source: { label: "NVCA Voting Agreement", url: "https://nvca.org/model-legal-documents/" },
    nuance: `Board control is about COMPOSITION, not ownership percentage. A typical early structure is two founders, one investor, or two-founders / one-investor / one-independent; who fills the independent seat can decide tie-breaks.`,
    verified: false,
  },
  {
    section: "diligence-terms",
    name: "Anti-Dilution (Full-Ratchet vs Weighted-Average)",
    slug: "anti-dilution",
    subtitle: "Down-round protection that reprices earlier investors' shares",
    difficulty: "ADVANCED",
    sortOrder: 4,
    whatItIs: `Anti-dilution provisions protect earlier investors if the company later sells shares at a LOWER price than they paid (a "down round"). They work by retroactively lowering the price at which the earlier investor's preferred shares convert to common, effectively granting them more shares to compensate. There are two flavors that differ in how aggressive that adjustment is.`,
    whyItMatters: `Anti-dilution decides who absorbs the pain of a down round, the protected investor or everyone else (founders and employees). The "full-ratchet" version can be brutally dilutive to founders, so which version a term sheet uses is a term worth fighting over.`,
    flashcardShort: `Down-round protection that reprices earlier investors' shares.`,
    flashcardDefinition: `A clause that protects earlier investors in a down round by lowering their conversion price, either fully (full-ratchet) or partially (weighted-average).`,
    source: { label: "NVCA model docs; anti-dilution explainer (Growth Equity Interview Guide)", url: "https://growthequityinterviewguide.com/venture-capital/venture-capital-term-sheets/anti-dilution" },
    nuance: `FULL-RATCHET resets the earlier investor's conversion price all the way down to the new lower price, regardless of how few shares were sold, maximally founder-punishing and now rare. WEIGHTED-AVERAGE (the market standard) adjusts only partially, scaled by the SIZE of the down round; "broad-based" (counts options and convertibles in the share base) is milder and standard, while "narrow-based" is harsher. Broad-based formula: NCP = OCP x (A + B) / (A + C), where A = shares outstanding before, B = new money / old price, C = new shares actually issued.`,
    verified: false,
  },
  {
    section: "diligence-terms",
    name: "Drag-Along / Tag-Along",
    slug: "drag-along-tag-along",
    subtitle: "Drag forces minorities to sell; tag lets them join",
    difficulty: "ADVANCED",
    sortOrder: 5,
    whatItIs: `These are two mirror-image share-transfer rights. A drag-along lets a majority (often the investors or founders) FORCE minority shareholders to join a sale of the company, so a buyer can acquire 100%. A tag-along lets minority shareholders ELECT to join a sale on the same terms when a major holder sells, so they are not left behind.`,
    whyItMatters: `Drag-along makes a clean exit possible by preventing a small holdout from blocking an acquisition. Tag-along protects small holders from being stranded while big holders cash out. Together they govern how share sales play out.`,
    flashcardShort: `Drag forces minorities to sell; tag lets them join.`,
    flashcardDefinition: `Paired rights where drag-along forces minority holders into a sale and tag-along lets them opt into one on equal terms.`,
    source: { label: "NVCA Voting Agreement and ROFR & Co-Sale Agreement", url: "https://nvca.org/model-legal-documents/" },
    nuance: `Drag-along (in the Voting Agreement) protects the BUYER / majority by compelling a full sale; tag-along / co-sale (in the ROFR & Co-Sale Agreement) protects the MINORITY by letting them ride along. Easy to mix up, they cut in opposite directions.`,
    verified: false,
  },
  {
    section: "diligence-terms",
    name: "ROFR (Right of First Refusal)",
    slug: "rofr",
    subtitle: "Company's first chance to buy shares before outsiders",
    difficulty: "INTERMEDIATE",
    sortOrder: 6,
    whatItIs: `A Right of First Refusal gives the company (and often its investors) the first chance to buy shares before an existing holder can sell them to an outside party. If a founder wants to sell stock, the company can match the offer and buy it first. It keeps control over who joins the cap table.`,
    whyItMatters: `ROFR stops shares from drifting to unwanted outside owners and lets insiders maintain control of the ownership base. Anyone holding startup equity should know it can limit their ability to sell.`,
    flashcardShort: `Company's first chance to buy shares before outsiders.`,
    flashcardDefinition: `A right letting the company or its investors purchase a holder's shares before they can be sold to a third party.`,
    source: { label: "NVCA ROFR & Co-Sale Agreement", url: "https://nvca.org/model-legal-documents/" },
    verified: false,
  },
  {
    section: "diligence-terms",
    name: "Down Round",
    slug: "down-round",
    subtitle: "Raising at a lower valuation than the prior round",
    difficulty: "INTERMEDIATE",
    sortOrder: 7,
    whatItIs: `A down round is a financing where a company raises money at a LOWER valuation than its previous round. It usually means the business stumbled or the market turned, and it triggers extra dilution and often anti-dilution protections for earlier investors. The 2022-2023 market produced many of them.`,
    whyItMatters: `Down rounds are painful and stigmatized: they dilute founders heavily, can demoralize employees (whose options may go underwater), and signal trouble. How the anti-dilution terms are written determines just how much it hurts.`,
    flashcardShort: `Raising at a lower valuation than the prior round.`,
    flashcardDefinition: `A funding round priced at a lower valuation than the company's previous round, triggering extra dilution and anti-dilution adjustments.`,
    source: { label: "Investopedia, Down Round", url: "https://www.investopedia.com/terms/d/downround.asp" },
    nuance: `A down round is what triggers anti-dilution clauses; under full-ratchet it can be devastating to founders, while weighted-average softens the blow.`,
    verified: false,
  },
  {
    section: "diligence-terms",
    name: "Secondary",
    slug: "secondary",
    subtitle: "Selling existing shares, not issuing new ones",
    difficulty: "INTERMEDIATE",
    sortOrder: 8,
    whatItIs: `A secondary is the sale of EXISTING shares from one investor or employee to another buyer, rather than the company issuing new shares to raise money (that is a "primary"). The cash goes to the seller, not into the company. It is how early shareholders get liquidity before an IPO or acquisition.`,
    whyItMatters: `Secondaries let founders and early employees take some money off the table during long pre-exit periods, and let new investors buy in. They do not raise capital for the company, which is the key distinction.`,
    flashcardShort: `Selling existing shares, not issuing new ones.`,
    flashcardDefinition: `A transaction in which existing shareholders sell their shares to another buyer, providing liquidity without raising new capital for the company.`,
    source: { label: "Investopedia, Secondary Market", url: "https://www.investopedia.com/terms/s/secondarymarket.asp" },
    nuance: `Key contrast: a PRIMARY sale issues new shares and the money goes to the company; a SECONDARY sells existing shares and the money goes to the selling shareholder.`,
    verified: false,
  },
  {
    section: "diligence-terms",
    name: "Exit (M&A vs IPO)",
    slug: "exit-ma-ipo",
    subtitle: "Turning equity into cash via acquisition or IPO",
    difficulty: "FUNDAMENTALS",
    sortOrder: 9,
    whatItIs: `An exit is the event where investors and founders finally turn their equity into cash or liquid stock. The two main routes are an M&A exit (the company is acquired by another company) and an IPO (the company sells shares to the public and lists on a stock exchange). M&A is far more common; IPOs are rarer and reserved for the largest companies.`,
    whyItMatters: `The exit is the whole point of venture investing; it is when returns (DPI, the carry, founder wealth) actually get realized. The type and size of exit determines who gets paid and how much, governed by the liquidation-preference stack.`,
    flashcardShort: `Turning equity into cash via acquisition or IPO.`,
    flashcardDefinition: `The liquidity event that realizes investor and founder returns, either an acquisition (M&A) or a public listing (IPO).`,
    source: { label: "Investopedia, IPO", url: "https://www.investopedia.com/terms/i/ipo.asp" },
    nuance: `M&A (acquisition) is the common path and can happen at any size; an IPO is rarer, reserved for larger companies, and is a listing rather than a sale. The liquidation-preference stack decides who gets paid first in either case.`,
    verified: false,
  },
];
