/**
 * One-sentence flashcard "front-definition" shorts for all 57 concepts.
 *
 * These are shown by default on the back of a flashcard for quick recall.
 * The longer FLASHCARD_DEFINITIONS appear when the user expands the card.
 *
 * Style:
 *   - One sentence. Definitional, not a tagline.
 *   - Concise and brief. If a phrase can be dropped without losing the core
 *     definition, drop it.
 *   - No em dashes (—). Use commas or semicolons instead.
 *
 * Keyed by concept slug for lookup during seeding.
 */

export const FLASHCARD_SHORTS: Record<string, string> = {
  // ── FUNDAMENTALS / Core Architecture ──────────────────────────────────
  transformers:
    "The neural network architecture behind every modern AI model.",

  "attention-mechanisms":
    "The algorithm that lets a model weigh how much each word matters to every other word.",

  tokens:
    "The small chunks of text a model reads and generates, usually a word or part of a word.",

  embeddings:
    "Numerical vectors representing meaning, where similar concepts sit close together.",

  // ── FUNDAMENTALS / Training Process ───────────────────────────────────
  "pre-training":
    "The initial training stage where a model learns to predict the next word from trillions of words of text.",

  rlhf: "Post-training that uses human preferences to turn a base model into a usable assistant.",

  rlvr: "Training that teaches models to reason step by step by rewarding verifiably correct answers.",

  // ── FUNDAMENTALS / Model Types ────────────────────────────────────────
  "base-models":
    "A model fresh from pre-training, with no instruction-tuning applied.",

  "instruction-tuned-models":
    "A base model fine-tuned to reliably follow instructions and behave like an assistant.",

  "reasoning-models":
    "Instruction-tuned models further trained to think step by step before answering.",

  // ── FUNDAMENTALS / Key Concepts ───────────────────────────────────────
  "system-prompts":
    "Hidden instructions given to a model before any user message that set its rules and persona.",

  "context-windows":
    "The maximum amount of text a model can see at once, measured in tokens.",

  parameters:
    "The learned numerical weights inside a model that encode what it knows.",

  "training-vs-inference":
    "Training updates a model's weights on data; inference uses the trained model to generate outputs.",

  hallucinations:
    "When a model confidently generates information that isn't true.",

  jailbreaking:
    "Crafting prompts that bypass a model's safety training or system prompt.",

  // ── FUNDAMENTALS / Capabilities ───────────────────────────────────────
  "tool-use":
    "A model's ability to call external code or APIs during a conversation.",

  "agentic-capabilities":
    "A model running in a loop with tools to complete multi-step tasks autonomously.",

  multimodality:
    "A model's ability to process images, audio, or video in addition to text.",

  // ── FUNDAMENTALS / Industry Basics ────────────────────────────────────
  "major-ai-players":
    "The three labs at the frontier of AI in 2026: OpenAI, Google DeepMind, and Anthropic.",

  "open-source-vs-open-weights":
    "Open source means everything is public; open weights means only the trained model file is downloadable.",

  wrapper:
    "A product built mostly by calling someone else's AI API, with little proprietary tech of its own.",

  // ── FUNDAMENTALS / Practical Skills ───────────────────────────────────
  "prompt-engineering":
    "The craft of writing inputs that reliably produce the outputs you want from a model.",

  "api-basics":
    "Calling a model from code by sending HTTP requests with messages, model choice, and parameters.",

  rag: "A pattern that retrieves relevant documents and injects them into a model's context to ground its answers.",

  // ── INTERMEDIATE / Hardware & Compute ─────────────────────────────────
  gpus: "Parallel-processing chips originally built for graphics, now the dominant hardware for AI training.",

  tpus: "Google's custom AI chips, purpose-built for the matrix math that neural networks run on.",

  accelerators:
    "Specialized hardware like GPUs and TPUs that makes AI training and inference feasible at scale.",

  "training-costs":
    "The hundreds of millions of dollars it takes to pre-train a frontier model.",

  "training-vs-inference-compute":
    "Training needs massive memory for gradients; inference only needs a forward pass and can be batched.",

  // ── INTERMEDIATE / Scaling & Data ─────────────────────────────────────
  "scaling-laws":
    "Empirical rules that predict how performance improves as parameters, data, and compute scale up.",

  "synthetic-data":
    "Training data generated by an AI model rather than collected from humans.",

  "fine-tuning":
    "Continuing training on a pre-trained model with a task-specific dataset to specialize it.",

  // ── INTERMEDIATE / Evaluation & Alignment ─────────────────────────────
  "benchmarking-llms":
    "Standardized test suites used to measure and compare model capabilities.",

  "ai-alignment":
    "The challenge of making sure AI systems actually do what humans want as they get more capable.",

  agi: "Artificial General Intelligence, commonly defined as AI that can perform any cognitive task a human can.",

  // ── INTERMEDIATE / Geopolitics & Regulation ───────────────────────────
  "us-china-ai-race":
    "The strategic competition between the US and China over AI dominance.",

  "export-controls":
    "US restrictions on selling advanced AI chips and chipmaking equipment to China.",

  "ai-regulation":
    "Government policy that determines where, how, and how fast AI companies can build and deploy.",

  // ── INTERMEDIATE / Ethics & Responsibility ────────────────────────────
  "bias-training-data":
    "Biases in training data that get learned by the model and show up in its outputs.",

  "copyright-ip":
    "Unresolved legal questions about whether training on copyrighted content is fair use.",

  "privacy-implications":
    "The risks of AI systems memorizing, leaking, or exposing personal data.",

  // ── INTERMEDIATE / Practical Decision-Making ──────────────────────────
  "evaluating-llm-solutions":
    "Rigorously checking whether an AI solution actually solves the problem, beyond a convincing demo.",

  "cost-deployment-tradeoffs":
    "The decisions around API vs. self-hosted, model tier, and cost controls that shape AI product economics.",

  "model-selection":
    "A framework for choosing between prompting, RAG, fine-tuning, and self-hosting for a given task.",

  // ── ADVANCED / Modern Non-LLM AI ──────────────────────────────────────
  "image-video-generation":
    "AI that creates images or video from text prompts, typically using diffusion models.",

  "world-models":
    "AI systems that learn to predict how an environment responds to actions.",

  "autonomous-driving":
    "Self-driving vehicle systems that combine perception, prediction, planning, and control.",

  "alphafold-biomedical-ai":
    "DeepMind's Nobel-winning model that solved protein structure prediction.",

  "robotics-embodied-ai":
    "AI applied to physical robots that need to perceive, plan, and act in the real world.",

  // ── ADVANCED / Advanced Training Mechanics ────────────────────────────
  "emergent-abilities":
    "Capabilities that appear suddenly at certain model scales rather than improving gradually.",

  "in-context-learning":
    "A model's ability to learn a new task from a few examples in the prompt, with no weight updates.",

  "continual-learning":
    "The unsolved problem of training a model on new information without it forgetting what it knew.",

  "fine-tuning-specifics":
    "The technical mechanics of fine-tuning, including efficient methods like LoRA and QLoRA.",

  // ── ADVANCED / Research & Meta-Skills ─────────────────────────────────
  "reading-research-papers":
    "Extracting value from AI papers by skimming abstract, figures, and conclusion before diving deeper.",

  "filtering-ai-hype":
    "Separating real capability gains from marketing, cherry-picked demos, and media distortion.",

  interpretability:
    "The research area focused on understanding what a model is actually doing internally.",
};
