// Curated Themes facet for the Trend Tracker (LOCKED).
// Source of truth: docs/plans/complete/TREND_TRACKER_REDESIGN_PLAN.md section 3.
//
// Themes are a plain-language, display-only facet (one or two tags per trend)
// that replaces the momentumLabel lifecycle stage in the UI. They say what a
// trend touches and form a second axis orthogonal to the AI / Tech / Capital
// category (an AI trend and a Capital trend can both be "Markets").
//
// This lives as a slug-keyed side map, NOT folded into prisma/seed-data/trends.ts,
// because trends.ts is auto-generated by scripts/build-trends-seed.ts from
// research JSON that has no themes field; a hand edit there would be overwritten.
// scripts/seed-trend-themes.ts writes these values to the `themes` column and
// touches nothing else (status, momentumLabel, curatedAt, contentHash all frozen).

/**
 * The locked Themes vocabulary: 11 tags, each mapped to a tile color in the UI
 * layer (not here, this module is data-only). "Security" and "Creators" are
 * reserved: no current trend uses them, but they stay in the set for trends the
 * cron adds later (an AI-enabled cyberattack -> Security; an AI copyright fight
 * -> Creators).
 */
export const THEME_VOCAB = [
  "Markets", // valuations, deals, IPOs, funding, liquidity
  "Builders", // developers, engineers, the people shipping
  "Jobs", // labor, automation, who does the work
  "Consumers", // everyday products and the people using them
  "Infrastructure", // compute, chips, energy, the physical layer
  "Science", // research frontiers, discovery, the lab
  "Safety", // risk, alignment, misuse, the high-stakes harms
  "Policy", // regulation, law, governments, courts
  "Geopolitics", // nations, trade, export controls, power
  "Security", // cyber, fraud, defense, attacks (reserved)
  "Creators", // artists, media, IP, the culture industry (reserved)
] as const;

export type Theme = (typeof THEME_VOCAB)[number];

/**
 * slug -> one or two themes, exactly as locked in section 3's table (ordered by
 * momentum then name, the list display order). Per-trend wording can be tailored
 * later; the vocabulary itself is fixed.
 */
export const TREND_THEMES: Record<string, Theme[]> = {
  "ai-coding-agents-replace-autocomplete": ["Builders", "Jobs"],
  "trillion-dollar-ai-ipo-pipeline": ["Markets"],
  "ai-mega-round-concentration": ["Markets"],
  "ai-chip-supercycle-custom-silicon": ["Infrastructure", "Markets"],
  "big-tech-ai-capex-versus-revenue-mismatch": ["Markets", "Infrastructure"],
  "model-context-protocol-standard": ["Builders"],
  "humanoid-robots-leave-the-lab": ["Jobs", "Consumers"],
  "open-weight-models-frontier-quality": ["Builders", "Geopolitics"],
  "post-training-revolution-rl-over-rlhf": ["Science", "Builders"],
  "agentic-ai-goes-production": ["Builders", "Jobs"],
  "inference-time-scaling-reasoning-models": ["Science", "Infrastructure"],
  "power-grid-binding-constraint-ai": ["Infrastructure", "Policy"],
  "small-language-models-on-device-ai": ["Consumers", "Builders"],
  "ai-drug-discovery-protein-science": ["Science", "Consumers"],
  "long-context-windows-1m-10m-tokens": ["Builders", "Science"],
  "mechanistic-interpretability-goes-mainstream": ["Safety", "Science"],
  "nuclear-power-smrs-ai-data-centers": ["Infrastructure", "Policy"],
  "physical-ai-robot-world-models": ["Science", "Builders"],
  "synthetic-data-default-pipeline": ["Builders", "Science"],
  "ai-smart-glasses-race": ["Consumers", "Markets"],
  "ai-safety-evaluation-crisis": ["Safety", "Policy"],
  "magnificent-seven-concentration-and-rotation": ["Markets"],
};
