/**
 * Build self-contained "finish" workflow scripts from the salvaged checkpoint.
 *
 * The original perspectives workflow re-runs survey/gate/research on every resume
 * (its internal cache does not rehydrate the dynamic fan-out), so resuming wastes
 * the whole budget redoing finished research and dies at the session limit. This
 * builder sidesteps that: it embeds the already-researched `camps` from
 * docs/research/perspectives-checkpoint.json and emits batch scripts that run ONLY
 * the cheap, still-missing tail stages, monotonically:
 *
 *   - perspectives already present -> run finalVerify only
 *   - otherwise                    -> campVerify (if missing) -> synth -> finalVerify
 *
 * Output shape per trend matches the original workflow, so the existing analyzer and
 * seed-writing steps work unchanged.
 *
 *   npx tsx scripts/workflows/build-perspectives-finish.ts [--batch-bytes 380000]
 *
 * Output: scripts/workflows/perspectives.finish.<n>.generated.js (one per batch)
 */
import { readFileSync, writeFileSync, readdirSync, unlinkSync } from "fs";
import { join } from "path";

const root = process.cwd();
const CKPT = join(root, "docs/research/perspectives-checkpoint.json");
const OUT_DIR = join(root, "scripts/workflows");

const argv = process.argv.slice(2);
const bbIdx = argv.indexOf("--batch-bytes");
const BATCH_BYTES = bbIdx !== -1 ? parseInt(argv[bbIdx + 1], 10) : 380000;

const ckpt = JSON.parse(readFileSync(CKPT, "utf8"));
const trends: any[] = Object.values(ckpt.trends);

// Only carry the fields the finish stages actually consume, to keep scripts small.
const slim = trends.map((t) => ({
  slug: t.slug,
  name: t.name,
  category: t.category,
  shape: t.shape,
  contestedness: t.contestedness,
  rationale: t.rationale,
  leans: t.leans,
  camps: t.camps,
  campVerify: t.campVerify, // {overallOk,falseBalance,notes} or null
  perspectives: t.perspectives, // present => only finalVerify needed
}));

// Greedy bin-pack by embedded byte size.
const batches: any[][] = [];
let cur: any[] = [];
let curBytes = 0;
for (const t of slim) {
  const b = JSON.stringify(t).length;
  if (cur.length && curBytes + b > BATCH_BYTES) {
    batches.push(cur);
    cur = [];
    curBytes = 0;
  }
  cur.push(t);
  curBytes += b;
}
if (cur.length) batches.push(cur);

// Remove any stale generated finish scripts first.
for (const f of readdirSync(OUT_DIR)) {
  if (/^perspectives\.finish\.\d+\.generated\.js$/.test(f)) unlinkSync(join(OUT_DIR, f));
}

function scriptFor(batch: any[], idx: number, total: number): string {
  const data = JSON.stringify(batch, null, 1);
  return `// @ts-nocheck
/* eslint-disable */
// GENERATED by build-perspectives-finish.ts. Batch ${idx + 1}/${total}.
// Runs ONLY the missing tail stages (campVerify -> synth -> finalVerify) over
// already-researched camps embedded below. Does NOT redo survey/gate/research.

export const meta = {
  name: 'trend-perspectives-finish-${idx + 1}',
  description: 'Finish Perspectives tail (synth + verify) for ${batch.length} pre-researched trends, batch ${idx + 1}/${total}',
  phases: [
    { title: 'CampVerify', detail: 'fact-check camps where it was not done yet (opus)' },
    { title: 'Synthesize', detail: 'write collapsed one-liner + full body per stance, dash-free (opus)' },
    { title: 'Final check', detail: 'verify the synthesized copy: claims, attributions, sources, dashes (opus)' },
  ],
}

const SYNTH_MODEL = 'opus'

const CAMP_VERIFY_SCHEMA = ${JSON.stringify(CAMP_VERIFY_SCHEMA)}
const SYNTH_SCHEMA = ${JSON.stringify(SYNTH_SCHEMA)}
const FINAL_VERIFY_SCHEMA = ${JSON.stringify(FINAL_VERIFY_SCHEMA)}

const DASH = ${JSON.stringify(DASH)}

const TRENDS = ${data}

log('Finishing Perspectives tail for ' + TRENDS.length + ' trends (batch ${idx + 1}/${total})')

const results = await pipeline(TRENDS, async (t) => {
  // Already synthesized in a prior run: only the final-copy verify is missing.
  if (t.perspectives && Array.isArray(t.perspectives.stances) && t.perspectives.stances.length) {
    const finalVerify = await agent(
      'Fact-check the FINAL published copy for "' + t.name + '" against its source camps. ' +
      'Final copy: ' + JSON.stringify(t.perspectives) + '\\nSource camps: ' + JSON.stringify(t.camps) + '\\n\\n' +
      'Confirm: every claim in each summary/body is supported by the camp evidence (no new unsupported claim the synth ' +
      'invented), every "who" attribution is accurate, and every source url is real (not fabricated). Then do a DASH SWEEP: ' +
      'set dashClean false if ANY em dash or en dash appears in intro, any summary, any body, or leans. ' +
      'Set ok true only if claims, attributions, and sources are clean AND dashClean is true. List concrete issues.',
      { schema: FINAL_VERIFY_SCHEMA, model: 'opus', phase: 'Final check', label: 'final:' + t.slug },
    )
    return {
      slug: t.slug, name: t.name, shape: t.shape, contestedness: t.contestedness, rationale: t.rationale,
      perspectives: t.perspectives,
      campVerify: t.campVerify || null,
      finalVerify: finalVerify || null,
    }
  }

  // Needs synthesis. Run campVerify only if we do not already have it.
  let campVerify = t.campVerify
  if (!campVerify) {
    campVerify = await agent(
      'Adversarially fact-check these camps on "' + t.name + '". Camps: ' + JSON.stringify(t.camps) + '\\n\\n' +
      'For each: is the stance REAL (actually held), ACCURATELY represented, and is it a STRAWMAN? Flag any misattribution ' +
      'or fabricated proponent/quote. Judge falseBalance: are they presented as equal when evidence clearly favors one? ' +
      'Set overallOk false if anything must be fixed before publishing.',
      { schema: CAMP_VERIFY_SCHEMA, model: 'opus', phase: 'CampVerify', label: 'verify:' + t.slug },
    )
  }

  const synth = await agent(
    'Write the on-page "Perspectives" section for "' + t.name + '" (' + t.category + '). Shape: ' + t.shape + '. ' +
    'Verified camps: ' + JSON.stringify(t.camps) + '. Evidence-leans: ' + (t.leans || '') + '. ' +
    'Verifier notes (apply these fixes, e.g. merge near-duplicate camps, drop unverified figures/quotes): ' +
    (campVerify ? campVerify.notes : 'n/a') + '.\\n\\n' +
    'For EACH stance produce: a trend-SPECIFIC label (for AI safety think doomers vs accelerationists; for capital, ' +
    'the bull case vs the bubble case; never generic "View A/B"); who holds it; a SUMMARY that is exactly ONE sentence ' +
    '(the collapsed view a reader sees before expanding); a BODY of the fuller reasoning; and up to 2 SOURCES drawn only ' +
    'from the camp evidence, each with a real url (omit any source without a real url, never invent one). ' +
    'Length: 2 stances get a ~2-3 sentence body each; 3-4 stances get ~1-2 sentences each. An optional one-sentence intro ' +
    'may name the axis. Convey asymmetry honestly through "leans" rather than forced balance. ' + DASH,
    { schema: SYNTH_SCHEMA, model: SYNTH_MODEL, phase: 'Synthesize', label: 'synth:' + t.slug },
  )
  if (!synth) {
    return { slug: t.slug, name: t.name, shape: t.shape, leans: t.leans, rationale: t.rationale, camps: t.camps,
      campVerify: campVerify || null, error: 'synth failed' }
  }

  const finalVerify = await agent(
    'Fact-check the FINAL published copy for "' + t.name + '" against its source camps. ' +
    'Final copy: ' + JSON.stringify(synth) + '\\nSource camps: ' + JSON.stringify(t.camps) + '\\n\\n' +
    'Confirm: every claim in each summary/body is supported by the camp evidence (no new unsupported claim the synth ' +
    'invented), every "who" attribution is accurate, and every source url is real (not fabricated). Then do a DASH SWEEP: ' +
    'set dashClean false if ANY em dash or en dash appears in intro, any summary, any body, or leans. ' +
    'Set ok true only if claims, attributions, and sources are clean AND dashClean is true. List concrete issues.',
    { schema: FINAL_VERIFY_SCHEMA, model: 'opus', phase: 'Final check', label: 'final:' + t.slug },
  )

  return {
    slug: t.slug, name: t.name, shape: t.shape, contestedness: t.contestedness, rationale: t.rationale,
    perspectives: { shape: t.shape, intro: synth.intro, stances: synth.stances, leans: synth.leans },
    campVerify: campVerify ? { overallOk: campVerify.overallOk, falseBalance: campVerify.falseBalance, notes: campVerify.notes } : null,
    finalVerify: finalVerify || null,
  }
})

return results
`;
}

// Schemas copied verbatim from perspectives.workflow.js so the finish stages match.
const CAMP_VERIFY_SCHEMA = {
  type: "object", additionalProperties: false,
  properties: {
    camps: { type: "array", items: { type: "object", additionalProperties: false,
      properties: { label: { type: "string" }, real: { type: "boolean" }, accurate: { type: "boolean" },
        strawman: { type: "boolean" }, issues: { type: "string" } },
      required: ["label", "real", "accurate", "strawman", "issues"] } },
    falseBalance: { type: "boolean" },
    overallOk: { type: "boolean" },
    notes: { type: "string" },
  },
  required: ["camps", "falseBalance", "overallOk", "notes"],
};

const SYNTH_SCHEMA = {
  type: "object", additionalProperties: false,
  properties: {
    intro: { type: "string", description: "one-sentence framing of the axis; may be empty" },
    stances: { type: "array", items: { type: "object", additionalProperties: false,
      properties: {
        label: { type: "string", description: "trend-specific stance label" },
        who: { type: "string", description: "attribution: camp/archetype or verified orgs" },
        summary: { type: "string", description: "ONE sentence; the collapsed-box view" },
        body: { type: "string", description: "the fuller reasoning shown when expanded" },
        sources: { type: "array", items: { type: "object", additionalProperties: false,
          properties: { title: { type: "string" }, url: { type: "string" } }, required: ["title", "url"] },
          description: "up to 2 real sources from the camp evidence; omit any without a real URL" },
      },
      required: ["label", "who", "summary", "body", "sources"] } },
    leans: { type: "string", description: "honest synthesis of where evidence points, or that it is genuinely contested" },
  },
  required: ["intro", "stances", "leans"],
};

const FINAL_VERIFY_SCHEMA = {
  type: "object", additionalProperties: false,
  properties: {
    ok: { type: "boolean" },
    dashClean: { type: "boolean" },
    issues: { type: "array", items: { type: "string" } },
  },
  required: ["ok", "dashClean", "issues"],
};

const DASH = `CRITICAL: use ZERO em dashes and en dashes in any member-facing text (intro, summary, body, leans). Use plain hyphens, commas, or periods only. Write numeric ranges as "18 to 24", never "18-24" with a dash glyph.`;

const total = batches.length;
batches.forEach((batch, i) => {
  const out = join(OUT_DIR, `perspectives.finish.${i + 1}.generated.js`);
  writeFileSync(out, scriptFor(batch, i, total));
  const bytes = JSON.stringify(batch).length;
  console.log(`batch ${i + 1}/${total}: ${batch.length} trends, ~${Math.round(bytes / 1000)}KB embedded -> ${out}`);
  console.log(`   ${batch.map((t) => t.perspectives ? t.slug + "(final-only)" : t.slug).join(", ")}`);
});
console.log(`\n${total} batch script(s) written.`);
