/**
 * Build "fix" workflow scripts for trends whose finalVerify flagged content defects
 * (fabricated stats, wrong-camp attributions, misread numbers). For each flagged
 * trend it re-synthesizes from the SAME cached camps, with the previous draft and
 * the fact-checker's exact issue list injected, under a hard constraint: every
 * statistic, name, org, and URL must already appear in the camp evidence. Then it
 * re-runs the final-copy verify. Output shape matches the original workflow so
 * consolidate-perspectives.ts merges it (passing versions supersede flagged ones).
 *
 *   npx tsx scripts/workflows/build-perspectives-fix.ts <out1> [out2 ...]
 *     (out files = the batch outputs carrying perspectives + finalVerify.issues)
 *
 * Reads camps/name/category/shape/leans/campVerify from
 *   docs/research/perspectives-checkpoint.json
 * Output: scripts/workflows/perspectives.fix.<n>.generated.js (one per batch)
 */
import { readFileSync, writeFileSync, readdirSync, unlinkSync } from "fs";
import { join } from "path";

const root = process.cwd();
const CKPT = join(root, "docs/research/perspectives-checkpoint.json");
const OUT_DIR = join(root, "scripts/workflows");
const BATCH_BYTES = 360000;

const outFiles = process.argv.slice(2);
if (outFiles.length === 0) throw new Error("pass the batch output file paths");

const ckpt = JSON.parse(readFileSync(CKPT, "utf8")).trends as Record<string, any>;

function loadResults(path: string): any[] {
  const parsed = JSON.parse(readFileSync(path, "utf8"));
  const arr = Array.isArray(parsed) ? parsed : parsed.result;
  if (!Array.isArray(arr)) throw new Error(`no result array in ${path}`);
  return arr;
}

// Collect the latest result per slug from the batch outputs.
const bySlug = new Map<string, any>();
for (const p of outFiles) for (const r of loadResults(p)) if (r && r.slug) bySlug.set(r.slug, r);

// Flagged = has perspectives but finalVerify failed (ok !== true).
const flagged: any[] = [];
for (const [slug, r] of bySlug) {
  const hasPersp = r.perspectives && Array.isArray(r.perspectives.stances) && r.perspectives.stances.length > 0;
  const fv = r.finalVerify;
  if (hasPersp && (!fv || fv.ok !== true)) {
    const ck = ckpt[slug] || {};
    flagged.push({
      slug,
      name: r.name || ck.name,
      category: ck.category,
      shape: r.shape || ck.shape,
      leans: ck.leans || (r.perspectives ? r.perspectives.leans : ""),
      camps: ck.camps, // the authoritative evidence base
      prev: r.perspectives, // the flawed draft to repair
      issues: fv ? fv.issues : [], // the fact-checker's exact findings
    });
  }
}

if (!flagged.length) {
  console.log("no flagged trends; nothing to fix");
  process.exit(0);
}

// Bin-pack by embedded byte size.
const batches: any[][] = [];
let cur: any[] = [];
let curBytes = 0;
for (const t of flagged) {
  const b = JSON.stringify(t).length;
  if (cur.length && curBytes + b > BATCH_BYTES) {
    batches.push(cur);
    cur = [];
    curBytes = 0;
  }
  cur.push(t);
  curBytes += b;
}
if (cur.length) batches.push(cur);

for (const f of readdirSync(OUT_DIR)) {
  if (/^perspectives\.fix\.\d+\.generated\.js$/.test(f)) unlinkSync(join(OUT_DIR, f));
}

const SYNTH_SCHEMA = {
  type: "object", additionalProperties: false,
  properties: {
    intro: { type: "string" },
    stances: { type: "array", items: { type: "object", additionalProperties: false,
      properties: {
        label: { type: "string" }, who: { type: "string" }, summary: { type: "string" }, body: { type: "string" },
        sources: { type: "array", items: { type: "object", additionalProperties: false,
          properties: { title: { type: "string" }, url: { type: "string" } }, required: ["title", "url"] } },
      },
      required: ["label", "who", "summary", "body", "sources"] } },
    leans: { type: "string" },
  },
  required: ["intro", "stances", "leans"],
};

const FINAL_VERIFY_SCHEMA = {
  type: "object", additionalProperties: false,
  properties: { ok: { type: "boolean" }, dashClean: { type: "boolean" }, issues: { type: "array", items: { type: "string" } } },
  required: ["ok", "dashClean", "issues"],
};

const DASH = `CRITICAL: use ZERO em dashes and en dashes in any member-facing text (intro, summary, body, leans). Use plain hyphens, commas, or periods only. Write numeric ranges as "18 to 24", never "18-24" with a dash glyph.`;

function scriptFor(batch: any[], idx: number, total: number): string {
  const data = JSON.stringify(batch, null, 1);
  return `// @ts-nocheck
/* eslint-disable */
// GENERATED by build-perspectives-fix.ts. Fix batch ${idx + 1}/${total}.
// Re-synthesizes flagged trends from cached camps with the fact-checker's issues
// injected, then re-verifies. Does NOT redo survey/gate/research.

export const meta = {
  name: 'trend-perspectives-fix-${idx + 1}',
  description: 'Repair ${batch.length} flagged Perspectives (remove fabrications, fix attributions) and re-verify, batch ${idx + 1}/${total}',
  phases: [
    { title: 'Re-synth', detail: 'rewrite copy using only camp-supported claims (opus)' },
    { title: 'Re-verify', detail: 'fact-check the repaired copy (opus)' },
  ],
}

const SYNTH_SCHEMA = ${JSON.stringify(SYNTH_SCHEMA)}
const FINAL_VERIFY_SCHEMA = ${JSON.stringify(FINAL_VERIFY_SCHEMA)}
const DASH = ${JSON.stringify(DASH)}

const TRENDS = ${data}

log('Repairing ' + TRENDS.length + ' flagged Perspectives (fix batch ${idx + 1}/${total})')

const results = await pipeline(TRENDS, async (t) => {
  const synth = await agent(
    'You previously wrote the on-page "Perspectives" section for "' + t.name + '" (' + t.category + '), but a fact-checker ' +
    'found specific defects. REWRITE the section to fix every one of them.\\n\\n' +
    'The verified source camps below are the ONLY permitted source of claims, statistics, named people/orgs, and source URLs:\\n' +
    JSON.stringify(t.camps) + '\\n\\n' +
    'Evidence-leans: ' + (t.leans || '') + '\\n\\n' +
    'Your previous draft (repair it, keep what was correct): ' + JSON.stringify(t.prev) + '\\n\\n' +
    'Fact-checker issues you MUST fix: ' + JSON.stringify(t.issues) + '\\n\\n' +
    'HARD RULES: (1) Every statistic, figure, date, named person, named organization, and source URL in your output MUST ' +
    'appear in the camp evidence above. If a detail is not in the camps, delete it rather than keep or replace it. ' +
    '(2) Do NOT invent a number to fix a wrong one; if the camps lack a precise figure, state it qualitatively. ' +
    '(3) Each stance "who" must name only proponents the camps assign to THAT camp; do not move a proponent across camps ' +
    'or add a name absent from the camps. (4) Every source must be a real url drawn from the camp evidence (omit any without one). ' +
    '(5) Keep the same shape (' + t.shape + ') and the honest, asymmetry-preserving "leans". For EACH stance produce a ' +
    'trend-specific label, who holds it, a one-sentence SUMMARY (collapsed view), a fuller BODY, and up to 2 SOURCES. ' + DASH,
    { schema: SYNTH_SCHEMA, model: 'opus', phase: 'Re-synth', label: 'resynth:' + t.slug },
  )
  if (!synth) {
    return { slug: t.slug, name: t.name, shape: t.shape, error: 'resynth failed' }
  }

  const finalVerify = await agent(
    'Fact-check the FINAL published copy for "' + t.name + '" against its source camps. ' +
    'Final copy: ' + JSON.stringify(synth) + '\\nSource camps: ' + JSON.stringify(t.camps) + '\\n\\n' +
    'Confirm: every claim in each summary/body is supported by the camp evidence (no new unsupported claim the synth ' +
    'invented), every "who" attribution is accurate (proponent assigned to the correct camp), and every source url is real ' +
    '(not fabricated). Then do a DASH SWEEP: set dashClean false if ANY em dash or en dash appears in intro, any summary, ' +
    'any body, or leans. Set ok true only if claims, attributions, and sources are clean AND dashClean is true. List concrete issues.',
    { schema: FINAL_VERIFY_SCHEMA, model: 'opus', phase: 'Re-verify', label: 'refinal:' + t.slug },
  )

  return {
    slug: t.slug, name: t.name, shape: t.shape,
    perspectives: { shape: t.shape, intro: synth.intro, stances: synth.stances, leans: synth.leans },
    finalVerify: finalVerify || null,
  }
})

return results
`;
}

const total = batches.length;
batches.forEach((batch, i) => {
  const out = join(OUT_DIR, `perspectives.fix.${i + 1}.generated.js`);
  writeFileSync(out, scriptFor(batch, i, total));
  const bytes = JSON.stringify(batch).length;
  console.log(`fix batch ${i + 1}/${total}: ${batch.length} trends, ~${Math.round(bytes / 1000)}KB embedded -> ${out}`);
  console.log(`   ${batch.map((t) => t.slug).join(", ")}`);
});
console.log(`\n${total} fix batch script(s) written for ${flagged.length} flagged trends.`);
